### ISSUE TITLE
NPE on repo update

### ISSUE THREAD

**Issue by g4s8** [artipie/management-api#39]
When trying to update or create repo via dashboard, management API throws NPE and returns 500 status:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at com.artipie.management.api.ApiRepoUpdateSlice.lambda$response$2(ApiRepoUpdateSlice.java:118)
	... 4 more
```

Artipie version is `v0.20`

**Comment by olenagerasimova** [comment]
@g4s8 what is the input? Could you please copy yaml here? 
Also, I cannot open my dashboard on central from chrome, it says 403. When I am tying curl with my login and password, it says 401. What can be the problem?

**Comment by g4s8** [comment]
> @g4s8 what is the input? Could you please copy yaml here?
> Also, I cannot open my dashboard on central from chrome, it says 403. When I am tying curl with my login and password, it says 401. What can be the problem?

@olenagerasimova I've fixed your permissions in central. The config file is default auto-generated config for binary repo:
```yaml
repo:
  type: file
  storage: default
  permissions:
    g4s8:
      - upload
      - download
    "*":
      - download
```
The request is:
```http
POST /api/repos/g4s8 HTTP/1.1
Host: central.artipie.com
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,ru;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 201
Origin: https://central.artipie.com
Referer: https://central.artipie.com/dashboard/g4s8/newbin?type=file
Pragma: no-cache
Cache-Control: no-cache

config=repo%3A%0D%0A++type%3A+file%0D%0A++storage%3A+default%0D%0A++permissions%3A%0D%0A++++g4s8%3A%0D%0A++++++-+upload%0D%0A++++++-+download%0D%0A++++%22*%22%3A%0D%0A++++++-+download%0D%0A&repo=newbin
```

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4.6`

**Comment by genryxy** [comment]
@g4s8 @olenagerasimova I've tried to build and run locally the latest version of Artipie but got the same error response

**Comment by olenagerasimova** [comment]
@genryxy are you sure you have rebuilt the image, updated source code?

**Comment by genryxy** [comment]
@olenagerasimova I fetched changes from git, ran `mvn package -Pdocker-build` and then `mvn install`, after that launched artipie using `artipie:1.0-SNAPSHOT`

**Comment by g4s8** [comment]
@olenagerasimova got the same error in new artipie release [v0.20.1](https://github.com/artipie/artipie/releases/tag/v0.20.1) which includes this fix (https://github.com/artipie/artipie/commit/1a051b9cdcd8b3651c8e6d059e9c9da56c79fa99)

```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "com.amihaiemil.eoyaml.YamlMapping.value(String)" because "repo" is null
	at com.artipie.management.api.ApiRepoUpdateSlice.lambda$response$2(ApiRepoUpdateSlice.java:118)
	... 4 more

```

**Comment by olenagerasimova** [comment]
@rultor release, tag=`0.4.7`
